# Root directory to locate the content
# Default is the root directory of the repository.
root: ./book
​
# Files to use as SUMMARY/README.
# (Relative to <root> directory)
structure:
  readme: README.md
  summary: SUMMARY.md